services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: Victorg224
      POSTGRES_PASSWORD: Victordanny123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
